name: Run static analysis and tests

on: [pull_request, push]

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo
          coverage: xdebug
          tools: composer
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --optimize-autoloader --no-progress

      - name: Ecs
        run: composer run ecs-dry -- --ansi
      
      - name: Psalm
        run: composer run psalm -- --output-format=github

      - name: Phpunit
        run: composer run test-cov -- --coverage-text